server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: true
    #false表示自己断就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: eureka
