server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    #false表示不向注册中心注册自己
    #可以理解为,所有企业都跑7001来注册公司,但是eureka自己不会向7001注册
    register-with-eureka: false
    #false表示自己断就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

