
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com    #eureka服务端的实例名称
  client: #false表示不向注册中心注册自己.可以理解为,所有企业都跑来入驻写字楼，但是eureka自己不会向写字楼交钱
    register-with-eureka: true
    #false表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务
      defaultZone: http://eureka7002.com:7002/eureka/
      #方便测试，临时改回单机模式，7002不再启动
      #defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护机制，保证当服务不可用时及时剔除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000
spring:
  application:
    name: eureka
