server:
  port: 80

eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: false #不注册EUREKA
    #    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    #    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

ribbon:
  ReadTimeout:  5000  #建立连接所用的时间,适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000 #指的是连接后从服务器读取到可用资源所用的时间

logging:
  level:
    # feign以什么级别,监控哪个接口
    com.ncamc.springcloud.service.PaymentFeignService: debug

